Tests/test convert docx
DeNederlandscheBank/nafigator pull request #73
Opened 2023-01-23 15:49 UTC by hmduerinck

2023-01-23 15:54 UTC, lesevereijns commented on tests/test_nafdocument.py
> +        tmp = NafDocument()
ipv tmp, zou je 'doc' willen gebruiken? Dan hebben we overal dezelfde term en zegt net iets meer. Credits naar Roy wel die het hiervoor een keer tegen mij heeft gezegd ;)

2023-01-23 15:54 UTC, lesevereijns approved these changes

2023-01-23 16:46 UTC, royklip requested changes

2023-01-23 16:46 UTC, royklip commented on tests/test_preprocessprocessor.py
It's always good to create at least one test class per test file

2023-01-23 16:46 UTC, royklip commented on tests/test_preprocessprocessor.py
>      pdf_exp_output = json.load(data_file)
These can be converted to fixtures or set them as attributes in your test class

2023-01-23 16:46 UTC, royklip commented on tests/test_preprocessprocessor.py
> +        actual_output = params[key_output]
You could rewrite this as:
```
actual_output = params[key_output]
if isinstance(params[key_output], bytes):
    actual_output  = actual_output.decode("utf-8")
```

But it is a preference thing ;)

2023-01-23 17:08 UTC, hmduerinck commented on tests/test_nafdocument.py
> +        tmp = NafDocument()
hahaha mooi, dan heb je ze niet aangepast. Dit zijn volgens mij jou testen. Ze staan hier in omdat ik een merge conflict heb opgelost ;). Mag je gelijk na deze merge oefenen met een nieuwe branch :P

2023-01-23 17:19 UTC, hmduerinck commented on tests/test_preprocessprocessor.py
check

2023-01-24 08:43 UTC, royklip approved these changes

2023-01-24 09:00 UTC, merged